title:              진예진의 고군분투 개발기
email:              yeen0606@gmail.com
description:        부지런한 사람이 되고싶다...
author:             Yejin Jin
baseurl:            "/"
url:                "https://JinYeJin.github.io"

# Social Profiles
# twitter_username:   SBootstrap
instagram_username: jinjinye_jin
github_username:    JinYeJin
facebook_username:  jinjinyejinjin
linkedin_username:  yeen666

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
theme:              minima
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
